- name: docker build and push
  hosts: http://35.178.32.219:8080   # Replace with the hostname or IP address of your target server
  become: yes  # Run tasks with sudo privileges

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes   

    - name: Install Docker
      apt:
       name: docker.io
       state: present

    - name: Build Docker Image
      command: docker build -t petstore .
      args:
        chdir: /var/lib/jenkins/workspace/petstore

    - name: tag image
      command: docker tag petstore:latest lloyddigital/petstore:latest 

    - name: Log in to Docker Hub
      docker_login:
        registry_url: https://index.docker.io/v1/
        username: lloyddigital
        password: M&^*vDJw$hB4*3K6
      register: docker_login_result

    - name: Push image
      command: docker push lloyddigital/petstore:latest

    - name: Run container
      command: docker run -d --name pet1 -p 8081:8080 lloyddigital/petstore:latest

    - name: Deploy Kubernetes Application
      hosts: k8s  # Replace with your target Kubernetes master host or group
      gather_facts: yes  # Gather facts about the target host